/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab1BCom2EjO6;

import static Lab1BCom2EjO6.Menu.listaProductos;
import java.awt.event.ItemListener;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author juani
 */
public class GestionProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestionProductos
     */
    public GestionProductos() {
        initComponents();
        cargarCombo();

        //Formulario();
        jtDes.setEnabled(false);
        jtPre.setEnabled(false);
        jtSto.setEnabled(false);
        jcbCat.setEnabled(false);
        jbGua.setEnabled(false);
        jbNue.setEnabled(false);
        jbEli.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtCod = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtDes = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtPre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtSto = new javax.swing.JTextField();
        jbNue = new javax.swing.JButton();
        jbGua = new javax.swing.JButton();
        jbEli = new javax.swing.JButton();
        jbSal = new javax.swing.JButton();
        jcbCat = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Carga de Productos");

        jLabel2.setText("Codigo:");

        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Descripcion:");

        jtDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDesActionPerformed(evt);
            }
        });

        jLabel4.setText("Precio:");

        jLabel5.setText("Categoria:");

        jLabel6.setText("Stock:");

        jbNue.setText("NUEVO");

        jbGua.setText("GUARDAR");
        jbGua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuaActionPerformed(evt);
            }
        });

        jbEli.setText("ELIMINAR");
        jbEli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliActionPerformed(evt);
            }
        });

        jbSal.setText("SALIR");
        jbSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jbNue)))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtPre, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtDes, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSal)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtSto, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jcbCat, javax.swing.GroupLayout.Alignment.LEADING, 0, 87, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtCod, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jbGua)
                                                .addGap(52, 52, 52)
                                                .addComponent(jbEli))
                                            .addComponent(jLabel1))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addContainerGap(179, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jtDes, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtPre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jtSto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNue)
                    .addComponent(jbGua)
                    .addComponent(jbEli)
                    .addComponent(jbSal))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDesActionPerformed

    private void jbGuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuaActionPerformed
        // TODO add your handling code here:

        Productos nuevo = new Productos();
        nuevo = agregarProducto();
        agregarProductoAlArreglo(nuevo);
        JOptionPane.showMessageDialog(this, "Producto Cargado con Exito");

    }//GEN-LAST:event_jbGuaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        busquedaCodigo();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbSalActionPerformed

    private void jbEliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliActionPerformed
        // TODO add your handling code here:
        
        int codigo = Integer.parseInt(jtCod.getText());

    // Buscar el producto en la lista de productos y eliminarlo
    for (Productos prod : Menu.listaProductos) {
        if (prod.getCodigo() == codigo) {
            Menu.listaProductos.remove(prod);
            JOptionPane.showMessageDialog(this, "Producto eliminado con éxito");
            limpiarCampos();
            return; // Salir del bucle una vez que se elimine el producto
        }
    }

    // Si no se encuentra el producto, mostrar un mensaje de error
    JOptionPane.showMessageDialog(this, "Producto no encontrado");
        
    }//GEN-LAST:event_jbEliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbEli;
    private javax.swing.JButton jbGua;
    private javax.swing.JButton jbNue;
    private javax.swing.JButton jbSal;
    private javax.swing.JComboBox<Rubro> jcbCat;
    private javax.swing.JTextField jtCod;
    private javax.swing.JTextField jtDes;
    private javax.swing.JTextField jtPre;
    private javax.swing.JTextField jtSto;
    // End of variables declaration//GEN-END:variables

    private void cargarCombo() {
        jcbCat.addItem(Rubro.LIMPIEZA);
        jcbCat.addItem(Rubro.COMESTIBLES);
        jcbCat.addItem(Rubro.PERFUMERIA);
    }

    public boolean busquedaCodigo() {

        boolean encontrado = false;
        int i = 0;

        for (Productos prod : Menu.listaProductos) {
            String codigo = String.valueOf(prod.getCodigo());
            if (codigo.equals(jtCod.getText())) {
                JOptionPane.showMessageDialog(this, "Producto ya registrado");
                encontrado = true;

                jtDes.setText(prod.getDescripcion());
                double pre = prod.getPrecio();
                String preGua = String.valueOf(pre);
                jtPre.setText(preGua);
                int sto = prod.getStock();
                String stoGua = String.valueOf(sto);
                jtSto.setText(stoGua);
                jbEli.setEnabled(true);

                break;
            }
        }
        // Mostrar un mensaje si no se encuentra el producto
        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "Producto no registrado");
            jtDes.setEnabled(true);
            jtPre.setEnabled(true);
            jtSto.setEnabled(true);
            jcbCat.setEnabled(true);
            jbGua.setEnabled(true);
            jbNue.setEnabled(false);
            jbEli.setEnabled(false);
            limpiarCampos();
        }
        return encontrado;
    }

    public static void agregarProductoAlArreglo(Productos producto) {
        Menu.listaProductos.add(producto);
    }

    public void limpiarCampos(){
        jtCod.setText("");
        jtDes.setText("");
        jtPre.setText("");
        jtSto.setText("");
    }
    
    public Productos agregarProducto() {
        int c = Integer.parseInt(jtCod.getText());
        String d = jtDes.getText();
        double p = Double.parseDouble(jtPre.getText());
        int s = Integer.parseInt(jtSto.getText());
        Rubro cat = (Rubro) jcbCat.getSelectedItem();
        Productos prod = new Productos(c, d, p, s, cat);
        Menu.listaProductos.add(prod);
        return prod;
    }

    public void habilitarCampos() {
        jtDes.setEnabled(true);
        jtPre.setEnabled(true);
        jtSto.setEnabled(true);
        jcbCat.setEnabled(false);
        jbGua.setEnabled(true);
    }

}
